apiVersion: v1
kind: Service
metadata:
  name: sample-nodejs-svc
  namespace: dev
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: sample-nodejs-svc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-nodejs-svc
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-nodejs-svc
  template:
    metadata:
      labels:
        app: sample-nodejs-svc
    spec:
      containers:
      - name: sample-nodejs-svc
        image: gcr.io/plogbook-k8s/nodejs-svc:latest
        ports:
        - containerPort: 8000
